"""esquema inicial

Revision ID: 0b628ed903d1
Revises: 
Create Date: 2026-08-29 17:00:38.527429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b628ed903d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oficios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('oficios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oficios_slug'), ['slug'], unique=True)

    op.create_table('profesionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('zona', sa.String(length=120), nullable=True),
    sa.Column('anios_experiencia', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', name='estadoprofesional'), nullable=False),
    sa.Column('saldo_creditos', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.String(length=300), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('telefono_referencia', sa.String(length=20), nullable=True),
    sa.Column('origen', sa.Enum('autorregistro', 'agregado_manual', name='origenprofesional'), nullable=False),
    sa.Column('token_acceso', sa.String(length=43), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profesionales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profesionales_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_profesionales_token_acceso'), ['token_acceso'], unique=True)

    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oficio', sa.String(length=80), nullable=False),
    sa.Column('zona', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('urgencia', sa.Enum('hoy', 'esta_semana', 'sin_prisa', name='urgencia'), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=120), nullable=True),
    sa.Column('telefono_cliente', sa.String(length=20), nullable=False),
    sa.Column('telefono_verificado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_oficio'), ['oficio'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_zona'), ['zona'], unique=False)

    op.create_table('zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('ciudad', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zonas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zonas_ciudad'), ['ciudad'], unique=False)
        batch_op.create_index(batch_op.f('ix_zonas_slug'), ['slug'], unique=True)

    op.create_table('desbloqueos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profesional_id', 'solicitud_id', name='uq_desbloqueo_prof_sol')
    )
    with op.batch_alter_table('desbloqueos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_desbloqueos_profesional_id'), ['profesional_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_desbloqueos_solicitud_id'), ['solicitud_id'], unique=False)

    op.create_table('movimientos_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('compra', 'consumo', name='tipomovimiento'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_credito', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_credito_profesional_id'), ['profesional_id'], unique=False)

    op.create_table('profesional_oficios',
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('oficio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('profesional_id', 'oficio_id')
    )
    op.create_table('profesional_zonas',
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('profesional_id', 'zona_id')
    )
    op.create_table('resenas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resenas_profesional_id'), ['profesional_id'], unique=False)

    op.create_table('suscripciones_push',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('suscripciones_push', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suscripciones_push_profesional_id'), ['profesional_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suscripciones_push', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suscripciones_push_profesional_id'))

    op.drop_table('suscripciones_push')
    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resenas_profesional_id'))

    op.drop_table('resenas')
    op.drop_table('profesional_zonas')
    op.drop_table('profesional_oficios')
    with op.batch_alter_table('movimientos_credito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_credito_profesional_id'))

    op.drop_table('movimientos_credito')
    with op.batch_alter_table('desbloqueos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_desbloqueos_solicitud_id'))
        batch_op.drop_index(batch_op.f('ix_desbloqueos_profesional_id'))

    op.drop_table('desbloqueos')
    with op.batch_alter_table('zonas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zonas_slug'))
        batch_op.drop_index(batch_op.f('ix_zonas_ciudad'))

    op.drop_table('zonas')
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_zona'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_oficio'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_creado_en'))

    op.drop_table('solicitudes')
    with op.batch_alter_table('profesionales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profesionales_token_acceso'))
        batch_op.drop_index(batch_op.f('ix_profesionales_estado'))

    op.drop_table('profesionales')
    with op.batch_alter_table('oficios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oficios_slug'))

    op.drop_table('oficios')
    # ### end Alembic commands ###
